<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ANDREW-PC" name="com.qtpselenium.framework.datadriven.portfolio.Test2" tests="1" failures="0" timestamp="8 Jul 2015 14:51:10 GMT" time="0.000" errors="1">
  <testcase name="test2" time="0.000" classname="com.qtpselenium.framework.datadriven.portfolio.Test2">
    <error type="org.testng.TestNGException" message="
Method public void com.qtpselenium.framework.datadriven.portfolio.Test2.test2(java.util.Hashtable) requires a @DataProvider named : suiteADataProvider in class com.qtpselenium.framework.datadriven.util.TestDataProvider">
      <![CDATA[org.testng.TestNGException: 
Method public void com.qtpselenium.framework.datadriven.portfolio.Test2.test2(java.util.Hashtable) requires a @DataProvider named : suiteADataProvider in class com.qtpselenium.framework.datadriven.util.TestDataProvider
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:274)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:430)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1300)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1015)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1104)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1195)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- test2 -->
</testsuite> <!-- com.qtpselenium.framework.datadriven.portfolio.Test2 -->
